# Generated by Django 4.0.3 on 2022-03-24 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0003_remove_curso_id_alter_curso_camada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Entregable',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
