# Generated by Django 4.0.3 on 2022-03-24 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0005_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudiante',
            new_name='Mago',
        ),
    ]
