# Generated by Django 4.0.3 on 2022-03-24 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0007_rename_profesion_profesor_materia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asignatura',
        ),
        migrations.DeleteModel(
            name='Extasis',
        ),
        migrations.DeleteModel(
            name='Mago',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
